trigger:
  branches:
    include:
      - main  # Replace with your main branch name

prerequisites:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the desired Python version

steps:
- task: DownloadSecureFile@1
  name: terraformInstallation
  displayName: 'Download Terraform'
  inputs:
    secureFile: 'terraform.zip'  # Upload Terraform zip file as secure file in Azure DevOps

- task: PowerShell@2
  displayName: 'Extract Terraform'
  inputs:
    targetType: 'inline'
    script: |
      Expand-Archive -Path $(terraformInstallation.secureFilePath) -DestinationPath $(Agent.ToolsDirectory)

- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'YourAzureSubscription'  # Replace with your Azure subscription name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)'

- task: PowerShell@2
  displayName: 'Terraform Init'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)/path/to/terraform/config
      "$(Agent.ToolsDirectory)/terraform init"

- task: PowerShell@2
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)/path/to/terraform/config
      "$(Agent.ToolsDirectory)/terraform plan -out=tfplan"

- task: PowerShell@2
  displayName: 'Terraform Apply'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)/path/to/terraform/config
      "$(Agent.ToolsDirectory)/terraform apply tfplan"
